language: cpp
env:
  global:
    - MAKEFLAGS="-j 2"
    - CTEST_OUTPUT_ON_FAILURE=1
os:
  - linux
  - osx
dist: xenial
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
